plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.chaquopy)
}

android {
    namespace = "com.androlua"
    compileSdk = 36
    // ndkVersion = "29.0.14033849"  // Temporarily disabled - NDK not available

    defaultConfig {
        applicationId = "com.androlua"
        minSdk = 24
        targetSdk = 29
        versionCode = 1
        versionName = "1.0"
        ndk {
        abiFilters += listOf("arm64-v8a")
    }
    }

    buildFeatures {
        viewBinding = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "4.1.2"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    // 便于侧载：release 用 debug keystore 签名（正式上架请换成自己的正式签名）
    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = false
        }
    }

    lint {
        // 本项目 targetSdk=29（兼容旧存储行为），不为 app store 政策类 lint 阻断 release 构建
        checkReleaseBuilds = false
        abortOnError = false
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.apksig)
    // 接管 Android 12+ 系统强制的那层启动画面（背景色 / 图标），见 SplashTheme
    implementation(libs.androidx.splashscreen)

    // AndroLua 可用的 Android 控件库（loadlayout 里 import 后即可用）
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("androidx.viewpager2:viewpager2:1.1.0")
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")
    implementation("androidx.drawerlayout:drawerlayout:1.2.0")
    implementation("androidx.coordinatorlayout:coordinatorlayout:1.2.0")
    implementation("androidx.fragment:fragment:1.8.5")

    // ---- 第三方库（Lua 脚本可 import，或走便捷全局函数）----
    // 图片加载
    implementation("com.github.bumptech.glide:glide:4.16.0")
    // 网络请求
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // 流式布局 FlexboxLayout（FlowLayout）
    implementation("com.google.android.flexbox:flexbox:3.0.0")
    // 矢量动画
    implementation("com.airbnb.android:lottie:6.4.1")

    // AndroLua + Flutter 桥：Flutter 模块（flutter_bridge）编译出的 AAR。
    // 需先执行 build_flutter_aar.sh / `cd flutter_bridge && flutter build aar` 生成本地仓库。
    debugImplementation("com.androlua.flutter_bridge:flutter_debug:1.0")
    releaseImplementation("com.androlua.flutter_bridge:flutter_release:1.0")
}
