plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.chaquopy)
}

android {
    namespace = "com.androlua"
    compileSdk = 36
    // ndkVersion = "29.0.14033849"  // Temporarily disabled - NDK not available

    defaultConfig {
        applicationId = "com.androlua"
        minSdk = 24
        targetSdk = 29
        versionCode = 1
        versionName = "1.0"
        ndk {
        abiFilters += listOf("arm64-v8a")
    }
    }

    buildFeatures {
        viewBinding = true
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "4.1.2"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    // 便于侧载：release 用 debug keystore 签名（正式上架请换成自己的正式签名）
    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = false
        }
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.apksig)

    // AndroLua + Flutter 桥：Flutter 模块（flutter_bridge）编译出的 AAR。
    // 需先执行 build_flutter_aar.sh / `cd flutter_bridge && flutter build aar` 生成本地仓库。
    debugImplementation("com.androlua.flutter_bridge:flutter_debug:1.0")
    releaseImplementation("com.androlua.flutter_bridge:flutter_release:1.0")
}
